### ISSUE TITLE
Summer League 2022 Snake Task List

### ISSUE THREAD

**Issue by bevns** [es-na-battlesnake/snakes#171]
- [x] #172
- [x] https://github.com/es-na-battlesnake/snakes/pull/180
- [x] https://github.com/es-na-battlesnake/snakes/pull/181
- [x] https://github.com/es-na-battlesnake/snakes/pull/182
- [x] https://github.com/es-na-battlesnake/snakes/pull/183
- [x] Decide on algorithm or library that we want to implement (Possibly https://github.com/lvn/hermes???) 
    - [x] Decided on https://github.com/brean/python-pathfinding 
- [x] #189
- [x] Name the snake
- [x] Pick port to use for the Summer League Snake

_Please edit the above list as new tasks are identified_
